[package]
name = "type_classes_outer_test"
version = "0.1.0"
authors = ["vengeq <vengeq@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
categorial ={path= "../"}

